services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: "Australia/Sydney"
    env_file:
      - ./.env
    volumes:
      - "./etc/pihole:/etc/pihole"
      - "./etc/dnsmasq.d:/etc/dnsmasq.d"
    networks:
      - backend
    dns:
      # fixes "[✗] DNS resolution is currently unavailable" - https://www.reddit.com/r/pihole/comments/zmm0rs/solution_cant_update_gravity_dns_resolution_is/
      - 127.0.0.1
    restart: unless-stopped

networks:
  backend:
    external: true
